Repository spatialos/UnrealGDKTestSuite, pull requests merged in 2018-10, with the labels that each got.

#110 UNR-407: Tests for the assignment of the generated `FUnrealObjectRef` contexts
  Game/Source/TestSuite/Tests/GDKTestRunner.cpp
  Game/Source/TestSuite/Tests/TestUObjectContexts.cpp
  Game/Source/TestSuite/Tests/TestUObjectContexts.h
Labels: size/L

#111 Add spatial cook folder
  Game/Config/DefaultGame.ini
Labels: size/XS

#112 Updates for 420 support
  Game/Source/TestSuite/Tests/TestBoolReplication.h
  Game/Source/TestSuite/Tests/TestCArrayReplication.h
  Game/Source/TestSuite/Tests/TestCharReplication.h
  Game/Source/TestSuite/Tests/TestEnumReplication.h
  Game/Source/TestSuite/Tests/TestFNameReplication.h
  Game/Source/TestSuite/Tests/TestFStringReplication.h
  Game/Source/TestSuite/Tests/TestFTextReplication.h
  Game/Source/TestSuite/Tests/TestFloatReplication.h
  Game/Source/TestSuite/Tests/TestIntReplication.h
  Game/Source/TestSuite/Tests/TestStaticComponentReplication.h
  Game/Source/TestSuite/Tests/TestTArrayReplication.h
  Game/Source/TestSuite/Tests/TestUObjectReplication.h
  Game/Source/TestSuite/Tests/TestUStructReplication.h
Labels: size/M

#113 Small fixes
  LaunchClient.bat
  README.md
  spatial/workers/unreal/spatialos.UnrealWorker.worker.json
Labels: size/S

#115 Streaming query on Singleton component
  spatial/workers/unreal/spatialos.UnrealClient.worker.json
  spatial/workers/unreal/spatialos.UnrealWorker.worker.json
Labels: size/XS

#116 Fix bad flag in worker config
  spatial/workers/unreal/spatialos.UnrealWorker.worker.json
Labels: size/XS

#117 Update streaming queries
  spatial/workers/unreal/spatialos.UnrealClient.worker.json
  spatial/workers/unreal/spatialos.UnrealWorker.worker.json
Labels: size/XS

#118 Updated readme
  README.md
Labels: size/M

#119 Docs/updated readme v2
  README.md
Labels: size/XS

#120 Upgrade to lbv2
  spatial/default_launch.json
Labels: size/M
