Repository spatialos/UnrealGDKTestSuite, pull requests merged in 2018-11, with the labels that each got.

#121 Upgrade to 13.3.1
  spatial/spatialos.json
Labels: size/XS

#122 Removed the clang-format
  .clang-format
Labels: size/M

#123 Removed redundant tests
  Game/Source/TestSuite/Tests/GDKTestRunner.cpp
  Game/Source/TestSuite/Tests/TestUObjectContexts.cpp
  Game/Source/TestSuite/Tests/TestUObjectContexts.h
Labels: size/L

#125 Server only singletons
  spatial/workers/unreal/spatialos.UnrealWorker.worker.json
Labels: size/XS

#127 Fix streaming queries
  spatial/workers/unreal/spatialos.UnrealWorker.worker.json
Labels: size/XS

#129 Update GlobalStateManager component to SingletonManager
  spatial/workers/unreal/spatialos.UnrealClient.worker.json
  spatial/workers/unreal/spatialos.UnrealWorker.worker.json
Labels: size/XS
