Repository spatialos/UnrealGDKTestSuite, pull requests merged in 2018-08, with the labels that each got.

#90 Regenerated typebinding changes -- synced with UNR-481 GDK branch
  Game/Source/TestSuite/Generated/SpatialTypeBinding_GDKTestRunner.cpp
  Game/Source/TestSuite/Generated/SpatialTypeBinding_PlayerState.cpp
  Game/Source/TestSuite/Generated/SpatialTypeBinding_RepCmdConfusion.cpp
  Game/Source/TestSuite/Generated/SpatialTypeBinding_S_TestUnderscoreClassName.cpp
  Game/Source/TestSuite/Generated/SpatialTypeBinding_TestActor.cpp
  Game/Source/TestSuite/Generated/SpatialTypeBinding_TestBoolReplication.cpp
  Game/Source/TestSuite/Generated/SpatialTypeBinding_TestCArrayReplication.cpp
  Game/Source/TestSuite/Generated/SpatialTypeBinding_TestCharReplication.cpp
  Game/Source/TestSuite/Generated/SpatialTypeBinding_TestEnumReplication.cpp
  Game/Source/TestSuite/Generated/SpatialTypeBinding_TestFNameReplication.cpp
  Game/Source/TestSuite/Generated/SpatialTypeBinding_TestFStringReplication.cpp
  Game/Source/TestSuite/Generated/SpatialTypeBinding_TestFTextReplication.cpp
  Game/Source/TestSuite/Generated/SpatialTypeBinding_TestFloatReplication.cpp
  Game/Source/TestSuite/Generated/SpatialTypeBinding_TestIntReplication.cpp
  Game/Source/TestSuite/Generated/SpatialTypeBinding_TestMulticastRPC.cpp
  Game/Source/TestSuite/Generated/SpatialTypeBinding_TestStaticComponentReplication.cpp
  Game/Source/TestSuite/Generated/SpatialTypeBinding_TestSuiteCharacter.cpp
  Game/Source/TestSuite/Generated/SpatialTypeBinding_TestSuiteGameStateBase.cpp
  Game/Source/TestSuite/Generated/SpatialTypeBinding_TestSuitePlayerController.cpp
  Game/Source/TestSuite/Generated/SpatialTypeBinding_TestTArrayReplication.cpp
  Game/Source/TestSuite/Generated/SpatialTypeBinding_TestUObjectReplication.cpp
  Game/Source/TestSuite/Generated/SpatialTypeBinding_TestUStructReplication.cpp
Labels: size/L

#91 Remove reset hack for vehicles
  Game/Source/TestSuite/VehicleCppPawn.cpp
  Game/Source/TestSuite/VehicleCppPawn.h
Labels: size/XS

#92 UNR-466: Updated the editor settings
  Game/Config/DefaultEditorPerProjectUserSettings.ini
  Game/Config/DefaultEditorSpatialGDK.ini
  Game/Source/TestSuite/Generated/SpatialTypeBinding_TestStaticComponentReplication.cpp
  Game/Source/TestSuite/Generated/SpatialTypeBinding_TestSuiteCharacter.cpp
  Game/Source/TestSuite/Generated/SpatialTypeBinding_TestSuitePlayerController.cpp
  spatial/snapshots/default.snapshot
Labels: size/M

#96 Update to bridge v2
  spatial/default_launch.json
  spatial/one_worker_test.json
  spatial/two_worker_test.json
Labels: size/XS

#98 unr-484 - Fixed test suite CI
  Game/Source/TestSuite/Generated/SpatialTypeBinding_TestSuiteCharacter.cpp
  Game/Source/TestSuite/Generated/SpatialTypeBinding_TestSuiteCharacter.h
  Game/Source/TestSuite/TestSuiteCharacter.cpp
  Game/Source/TestSuite/TestSuiteCharacter.h
  Game/Source/TestSuite/Tests/GDKTestRunner.cpp
  Game/Source/TestSuite/Tests/TestMulticastRPC.cpp
  Game/Source/TestSuite/Tests/TestMulticastRPC.h
  spatial/schema/improbable/unreal/generated/UnrealTestSuiteCharacter.schema
  spatial/schema/improbable/unreal/generated/UnrealTestSuiteCharacterTypes.schema
Labels: size/L

#99 UNR-498: Separate linux builds from windows builds in CI
  ci/build_linux.sh
  ci/build_windows.sh
  ci/prepare_build_environment.sh
Labels: size/M
