Repository spatialos/UnrealGDKTestSuite, pull requests merged in 2019-04, with the labels that each got.

#137 update the old uses of EntityRegistry to PackageMap
  Game/Source/TestSuite/TestSuiteCharacter.h
  Game/Source/TestSuite/TestSuiteCharacterSibling.h
  Game/Source/TestSuite/TestSuitePlayerController.cpp
  Game/Source/TestSuite/Tests/TestTArrayReplication.cpp
  Game/Source/TestSuite/Tests/TestUObjectReplication.cpp
  Game/Source/TestSuite/Tests/TestUStructReplication.cpp
  Game/Source/TestSuite/VehicleCppPawn.h
Labels: size/S

#138 Changed default protocol to TCP
  spatial/workers/unreal/spatialos.UnrealWorker.worker.json
Labels: size/XS

#139 bugfix/UNR-1242
  Game/Source/TestSuite/TestSuiteTestClasses.h
Labels: size/XS

#140 0.3.0 rc
  Game/Source/TestSuite/TestSuiteCharacter.h
  Game/Source/TestSuite/TestSuiteCharacterSibling.h
  Game/Source/TestSuite/TestSuitePlayerController.cpp
  Game/Source/TestSuite/TestSuiteTestClasses.h
  Game/Source/TestSuite/Tests/TestTArrayReplication.cpp
  Game/Source/TestSuite/Tests/TestUObjectReplication.cpp
  Game/Source/TestSuite/Tests/TestUStructReplication.cpp
  Game/Source/TestSuite/VehicleCppPawn.h
  spatial/workers/unreal/spatialos.UnrealWorker.worker.json
Labels: size/S

#141 Switch QBI default to on
  Game/Config/DefaultEngine.ini
  spatial/default_launch.json
  spatial/one_worker_test.json
  spatial/two_worker_test.json
Labels: size/M

#142 0.4.0
  Game/Config/DefaultEngine.ini
  spatial/default_launch.json
  spatial/one_worker_test.json
  spatial/two_worker_test.json
Labels: size/M
